FROM maven:3.9-amazoncorretto-17 AS build
WORKDIR /clustereddatawarehouse
COPY pom.xml .
RUN mvn dependency:go-offline
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:20
WORKDIR /serverside
COPY --from=build /clustereddatawarehouse/target/Clustereddatawarehouse-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "Clustereddatawarehouse-0.0.1-SNAPSHOT.jar"]
